
import { Translation, Language } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    nav: {
      home: "Home",
      about: "About",
      services: "Services",
      gallery: "Gallery",
      contact: "Contact",
      donate: "Donate",
    },
    hero: {
      welcome: "Welcome Home",
      subtitle: "A place of love, worship, and community. Join us this Sunday!",
      learnMore: "About Us",
      watchOnline: "Watch Online",
    },
    pastor: {
      title: "Our Leadership",
      name: "Pastor Biniam Asefaw",
      description: "Serving Berhane Wongel Dallas with a heart for God and people. Watch our latest sermons online.",
      watchSermons: "Watch Sermons",
    },
    bookAd: {
      newRelease: "NEW BOOK RELEASE",
      author: "By Pastor Biniam Asefaw",
      title: "The Voice of God",
      subtitle: "Hearing : Recognizing : Following",
      date: "November 2, 2025",
      contactLabel: "To get your copy, please contact:",
      buttonText: "Email to Order",
    },
    services: {
      title: "Join Us Sunday",
      subtitle: "We have two services every Sunday morning.",
      tigrinyaTitle: "Tigrinya Service",
      tigrinyaDesc: "A traditional and vibrant service conducted in Tigrinya.",
      englishTitle: "Young Adult Service",
      englishDesc: "A dynamic and engaging service for young adults in English.",
      time: "10:00 AM - 12:00 PM",
      moreServicesTitle: "Weekly Schedule",
      fridayTitle: "Teaching Service",
      fridayTime: "Friday 7:00 PM - 9:00 PM",
      sundayPrayerTitle: "Morning Prayer",
      sundayPrayerTime: "Sunday 8:30 AM - 10:00 AM",
      nightPrayerTitle: "Monthly Night Prayer",
      nightPrayerDesc: "Last Friday of the month (after teaching)",
      nightPrayerTime: "9:00 PM - 12:00 AM",
    },
    gallery: {
      title: "Our Community",
      subtitle: "Capturing moments of joy and fellowship.",
    },
    assistant: {
      title: "Spiritual Assistant",
      description: "Ask questions about faith, our church, or the Bible. We are here to help guide you on your spiritual journey.",
      placeholder: "Ask a question...",
      button: "Ask",
      loading: "Thinking...",
    },
    donate: {
      title: "Give Online",
      subtitle: "Support the mission and ministry of Berhane Wongel Dallas.",
      zelleLabel: "Donate via Zelle:",
      email: "Gospellightfinance@gmail.com",
      copyText: "Click to Copy Email",
      copiedText: "Copied!",
    },
    footer: {
      rights: "Berhane Wongel Dallas. All rights reserved.",
      connect: "Connect With Us",
      contact: "Visit Us",
      contactUs: "Contact",
      address: "11110 Garland Rd, Dallas, TX 75218",
      phone: "(214) 327-5700",
      hoursTitle: "Office Hours",
      weekdays: "Tue - Fri: 10:00 AM - 6:00 PM",
      sunday: "Sun: 10:00 AM - 12:00 PM",
      closed: "Mon & Sat: Closed",
    },
  },
  ti: {
    nav: {
      home: "መራሒ", 
      about: "ብዛዕባና", 
      services: "ኣገልግሎት", 
      gallery: "ስእልታት", 
      contact: "ርክብ", 
      donate: "ወፈያ", 
    },
    hero: {
      welcome: "እንቋዕ ብደሓን መጻእኩም",
      subtitle: "ቦታ ፍቕርን ኣምልኾን ሕብረትን። ንሰንበት ምሳና ሕበሩ!",
      learnMore: "ብዛዕባና",
      watchOnline: "ብኦንላይን ተከታተሉ",
    },
    pastor: {
      title: "መራሕና",
      name: "ፓስተር ቢንያም ኣሰፋው",
      description: "ንቤተ ክርስቲያን ብርሃነ ወንጌል ዳላስ ብፍቕሪ እግዚኣብሄርን ህዝብን ዘገልግል። ስብከታትና ብኦንላይን ተከታተሉ።",
      watchSermons: "ስብከታት ተመልከቱ",
    },
    bookAd: {
      newRelease: "ሓድሽ መጽሓፍ",
      author: "ብ ፓስተር ቢንያም ኣሰፋው",
      title: "ድምጺ ኣምላኽ",
      subtitle: "ምስማዕ ፡ ምልላይ ፡ ምስዓብ",
      date: "ሕዳር 2, 2025",
      contactLabel: "መጽሓፍ ንምርካብ ኣብዚ ተወከሱ:",
      buttonText: "ንምእዛዝ ኢመይል ጸሓፉ",
    },
    services: {
      title: "ንሰንበት ምሳና ሕበሩ",
      subtitle: "ኩሉ ሰንበት ንጉሆ ክልተ ኣገልግሎት ኣለና።",
      tigrinyaTitle: "ናይ ትግርኛ ኣገልግሎት",
      tigrinyaDesc: "ብቋንቋ ትግርኛ ዝካየድ ሓያልን ባህላዊን ኣምልኾ።",
      englishTitle: "ናይ መንእሰያት ኣገልግሎት",
      englishDesc: "ንመንእሰያት ዝኸውን ብቋንቋ እንግሊዝ ዝካየድ ኣገልግሎት።",
      time: "10:00 ንጉሆ - 12:00 ቀትሪ",
      moreServicesTitle: "ሰሙናዊ መደባት",
      fridayTitle: "ትምህርቲ መጽሓፍ ቅዱስ",
      fridayTime: "ዓርቢ 7:00 ምሸት - 9:00 ምሸት",
      sundayPrayerTitle: "ናይ ንጉሆ ጸሎት",
      sundayPrayerTime: "ሰንበት 8:30 ንጉሆ - 10:00 ንጉሆ",
      nightPrayerTitle: "ናይ ወርሒ ናይ ለይቲ ጸሎት",
      nightPrayerDesc: "መወዳእታ ዓርቢ ናይ ወርሒ (ድሕሪ ትምህርቲ)",
      nightPrayerTime: "9:00 ምሸት - 12:00 ለይቲ",
    },
    gallery: {
      title: "ማሕበረሰብና",
      subtitle: "ግዜ ኣምልኾን ሕብረትን ሓጎስን።",
    },
    assistant: {
      title: "መንፈሳዊ ሓጋዚ",
      description: "ብዛዕባ እምነት፣ ቤተ ክርስቲያንና ወይ መጽሓፍ ቅዱስ ሕቶታት ሕተቱ። ኣብ መንፈሳዊ ጉዕዞኹም ክንመርሓኩም ኣብዚ ኣለና።",
      placeholder: "ሕቶ ሕተቱ...",
      button: "ሕተት",
      loading: "ይሓስብ ኣሎ...",
    },
    donate: {
      title: "ወፈያ",
      subtitle: "ንተልእኾን ኣገልግሎትን ቤተ ክርስቲያን ብርሃነ ወንጌል ዳላስ ደግፉ።",
      zelleLabel: "ብ Zelle ወፈያ ንምግባር:",
      email: "Gospellightfinance@gmail.com",
      copyText: "ኢመይል ንምቕዳሕ ኣብዚ ጠውቑ",
      copiedText: "ተቐዲሑ!",
    },
    footer: {
      rights: "ቤተ ክርስቲያን ብርሃነ ወንጌል ዳላስ።",
      connect: "ምሳና ተራኸቡ",
      contact: "ኣድራሻ",
      contactUs: "ርክብ",
      address: "11110 Garland Rd, Dallas, TX 75218",
      phone: "(214) 327-5700",
      hoursTitle: "ናይ ስራሕ ሰዓታት",
      weekdays: "ሰሉስ - ዓርቢ: 10:00 ንጉሆ - 6:00 ምሸት",
      sunday: "ሰንበት: 10:00 ንጉሆ - 12:00 ቀትሪ",
      closed: "ሰኑይ & ቀዳም: ዕጹው",
    },
  },
};